name: unit_testing

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    container: argovis/ifremer-sync:nightly

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: unit_tests
        run: pytest tests/tests.py

